services:
- docker
env:
- IMAGE='iscdev/iscloc'
jobs:
  include:
  - stage: build&test
    script:
    - mkdir -p workdir
    - docker build -t ${IMAGE} .
    - docker run -d --name iscloc -v ${PWD}/workdir:/workdir ${IMAGE} /usr/src/iscloc/isf/isf_test_input2.dat
      /workdir/my_output.out
    - while true; do if docker logs iscloc | grep "ISC Locator finished"; then break;
      else sleep 10; fi done
    - head -n 50  workdir/my_output.out
    - docker run -d --name iscloc_rstt -e RSTT_SUPPORT=true -v ${PWD}/workdir:/workdir
      ${IMAGE} /usr/src/iscloc/isf/isf_test_input2.dat /workdir/my_output_rstt.out
    - while true; do if docker logs iscloc_rstt | grep "RSTT ISC Locator finished";
      then break; else sleep 60; fi done
    - head -n 50 workdir/my_output_rstt.out
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker tag ${IMAGE}:latest ${IMAGE}:stage
    - docker push ${IMAGE}:stage
  - stage: deploy
    if: branch = master
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker pull ${IMAGE}:stage
    - docker tag ${IMAGE}:stage ${IMAGE}:latest
    - docker push ${IMAGE}:latest
notifications:
  slack:
    rooms:
      secure: BTo8WbruG5kphcCQmDbxvqTvW+vRjPpD7acRP9cuwhihzUlRzHlXN4ToNZ55CIHMFHpKiSiddsjQYu5xF3qDVfVTlO8lf4u6Z0FZc9tGxAW5DAN9S7wn7ZaHZK1EDrNabeG7wDliTXt9gmxqMXYkRppP1mYkiKgvL0Y+0yKC5v4mrOpYorYt6RABNwTfVOU8/CmRIk9rg90RQNfQSn0WjJXRPm571POgJpHejg5CkufrThpvNWEh42LrUl7QJvjBxgHpPWbVPqeZiyHhjGnTCavDZUH+8RI9u8wSbvPmogPmkGUHU5VGCBaVkpb4C8Q82AiJEV0RZfWp9RnpbpKFi6agsSrOQeR8Y2mwW9CnLmZLA7rG+CiWbLyvRalK4MshbnhGh1yfBRyAx1Av8vdymzG8wDWpwHPjACb/l53K3CZ1oTKiTHF+BDTLj0fYw17xn7OJXYQz7bA0dCceVo0NtRk/s8dtSVZMcqqBxjHdZ5rSNKr8NuuGlSU/U5yCmHZAijXy1MmkK+LVZtC3l77CRvlJHUavB4ZuhiSwb4glvbgbTYoCcNkAnZjkSEuTooMRFs91aME5pYdxfMg4ccZoucactK2iIjXeCqmXNL6CE6i4WFNSHwiB9pXLUJeutHU548BO0b7rcnGxHTriEYtkuZtS7WpOuP4RVg8xOFCRQ0M=
