services:
- docker
env:
- IMAGE='iscdev/iscloc'
jobs:
  include:
  - stage: build&test
    script:
    - docker build -t ${IMAGE} .
    - docker run -d --name iscloc ${IMAGE} /usr/src/iscloc/isf/isf_test_input2.dat
      /usr/src/iscloc/isf/my_output.out
    - while true; do if docker logs iscloc | grep "ISC Locator finished"; then break;
      else sleep 10; fi done
    - docker run -d --name iscloc_rstt -e RSTT_SUPPORT=true ${IMAGE} /usr/src/iscloc/isf/isf_test_input2.dat
      /usr/src/iscloc/isf/my_output_rstt.out
    - while true; do if docker logs iscloc_rstt | grep "RSTT ISC Locator finished";
      then break; else sleep 10; fi done
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker tag ${IMAGE}:latest ${IMAGE}:stage
    - docker push ${IMAGE}:stage
  - stage: deploy
    if: branch = master
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker pull ${IMAGE}:stage
    - docker tag ${IMAGE}:stage ${IMAGE}:latest
    - docker push ${IMAGE}:latest
notifications:
  slack:
    secure: SkIZ4JzFpXFXuKzVLs1UXlLzx1rxVuBF64lewiz7cwj0/G9f9+TgODcN7hIs2LeSqGjQYCKWDVIVXQQ2gcwMV3msJuskArTdF85DT1LSBTbOBTQCyXMfqIdWXafUcmlzlakGXh28ecxTy3ujYpO1Jd/WS69+/aGSXNSmQsBHMouCtJ5SZer8bDml6pBYds8al6n6bTFhVipPXsPVzEtQ0lME20RXuQWekjx0lpF10VSBcxCVesgYhD/hHpYfYqosWxSbSVv1IbnXYell+8/7ohZV0p2YLwwPlxsliVtCEFRCxpAPXdnDn7QfgDNBILw+qiuD0tSrDWS9ntEuVqcQ+ebDLT8QSebyJlx7a/OqHe0M6cxYfjW2mkZ70S37tZj4UygjZAcWT0irqYye9nrp93DcTolTwfITtB/7kAzwv7GB7/EgbB4gsex6ydSPY6mz/XjQmBBDfcTPlhBW3LuWZS27Y52o3XTqNlOs/XqPi9PE0wNJDiZDCkr/Qmk57e5c947FWIEtdxNJDd3v4rTJoAUVpQ4EClrPDgOAvBTQuedugUyCjPcZ7Jiuddh/qQKztqQUJDgiNz1S4xz/l8n15uKzAeH2H9e1T1qHL0QhIhtKj61s5zULlSxZqh/NH9Dj3AUocSSk6M456lOP1v8/zGnBmymL/THA1/B6pZnAIFM=
